### ISSUE TITLE
0.4.1 fails to build on Debian (rustc 1.34.2)

### ISSUE THREAD

**Issue by victorjulien** [starkat99/widestring-rs#14]
0.4.0 was fine, but 0.4.1 breaks on 1.34.2:

```
    Compiling widestring v0.4.1
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
   --> /builds/inliniac/suricata-ci/suricata/rust/vendor/widestring/src/lib.rs:195:1
    |
195 | extern crate alloc;
    | ^^^^^^^^^^^^^^^^^^^
```

We use widestring in Suricata. We use a minimum of rustc 1.34.2 as this is what Debian stable uses and we want to make sure Debian can (continue to) package Suricata.

**Comment by starkat99** [comment]
0.4.1 has been yanked, and 0.4.2 released, which fixes the compile error. I set CI to test on 1.34.2 to prevent errors on Debian in future.

**Comment by victorjulien** [comment]
I can confirm 0.4.2 works again, thanks for the quick fix!
